### ISSUE TITLE
JS client has no documentation

### ISSUE THREAD

**Issue by krisbitney** [polywrap/javascript-client#86]
From a recent paid user study:
> The [readme](https://www.npmjs.com/package/@polywrap/client-js) of @polywrap/client-js has no docs, it leads to the package [repository](https://github.com/polywrap/javascript-client) polywrap/client-javascript, which has a link “Documentation” that leads to https://docs.polywrap.io/ which has a link Clients that leads back to polywrap/client-javascript repository.

The JS client used to have automatically-generated reference documentation in its readme, but it looks like it was removed at some point and was never replaced.

JS client readme: https://github.com/polywrap/javascript-client

The JS client should have more documentation. 
- What packages are in the JS client repo? Which do I need?
- What methods are available in the client?
- Which important plugins are available and where can I find them?
- What is the best way to use the client?
- etc.

**Comment by pileks** [comment]
Should be resolved by #87
